import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { useParams, useNavigate } from 'react-router-dom';
import { getInterviewDetails } from '../services/interviewService';

function ScoreRing({ score, label, color }) {
  const radius = 28;
  const circ = 2 * Math.PI * radius;
  const dash = ((score || 0) / 10) * circ;
  return (
    <div className="flex flex-col items-center gap-2">
      <div className="relative w-16 h-16">
        <svg width="64" height="64" viewBox="0 0 64 64" className="-rotate-90">
          <circle cx="32" cy="32" r={radius} fill="none" stroke="rgba(150,150,150,0.15)" strokeWidth="5" />
          <motion.circle
            cx="32" cy="32" r={radius} fill="none"
            stroke={color} strokeWidth="5"
            strokeDasharray={circ}
            initial={{ strokeDashoffset: circ }}
            animate={{ strokeDashoffset: circ - dash }}
            transition={{ duration: 1.2, ease: 'easeOut', delay: 0.2 }}
          />
        </svg>
        <div className="absolute inset-0 flex items-center justify-center">
          <span className="text-sm font-bold text-slate-900 dark:text-white">{score || 0}</span>
        </div>
      </div>
      <span className="text-xs text-slate-600 dark:text-slate-400 text-center font-medium">{label}</span>
    </div>
  );
}

const RECOMMENDATION_CONFIG = {
  'Strong Hire': { color: 'text-emerald-600 dark:text-emerald-400', bg: 'bg-emerald-500/10 border-emerald-500/30', icon: '🏆' },
  'Hire': { color: 'text-indigo-600 dark:text-indigo-400', bg: 'bg-indigo-500/10 border-indigo-500/30', icon: '✅' },
  'No Hire': { color: 'text-amber-600 dark:text-amber-400', bg: 'bg-amber-500/10 border-amber-500/30', icon: '⚠️' },
  'Strong No Hire': { color: 'text-rose-600 dark:text-rose-400', bg: 'bg-rose-500/10 border-rose-500/30', icon: '❌' },
};

export default function MockInterviewResults() {
  const { sessionId } = useParams();
  const navigate = useNavigate();
  const [interview, setInterview] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!sessionId) return;
    getInterviewDetails(sessionId).then((data) => {
      if (data.success) setInterview(data.interview);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, [sessionId]);

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex items-center justify-center text-slate-900 dark:text-slate-100 transition-colors">
        <div className="text-center">
          <div className="w-10 h-10 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-slate-600 dark:text-slate-400">Evaluating interview performance...</p>
        </div>
      </div>
    );
  }

  const eval_ = interview?.evaluation;
  if (!eval_) {
    return (
      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex items-center justify-center text-center px-4 text-slate-900 dark:text-slate-100 transition-colors">
        <div>
          <div className="text-5xl mb-4">📊</div>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-2">Evaluation Pending</h2>
          <p className="text-slate-600 dark:text-slate-400 mb-6">Your evaluation summary is being prepared.</p>
          <button onClick={() => navigate('/dashboard')} className="px-6 py-2.5 bg-indigo-600 text-white rounded-xl text-sm font-semibold">
            Back to Dashboard
          </button>
        </div>
      </div>
    );
  }

  const rec = RECOMMENDATION_CONFIG[eval_.hiringRecommendation] || RECOMMENDATION_CONFIG['No Hire'];

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 px-4 py-12 text-slate-900 dark:text-slate-100 transition-colors duration-300">
      <div className="max-w-3xl mx-auto space-y-6">
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-8">
          <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-2">Interview Evaluation Report 🎉</h1>
          <p className="text-slate-600 dark:text-slate-400">Detailed feedback generated by LearnSphere AI</p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-white dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 backdrop-blur-xl rounded-2xl p-8 text-center shadow-lg dark:shadow-xl transition-colors"
        >
          <div className="text-6xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 dark:from-indigo-400 dark:via-purple-400 dark:to-pink-400 mb-2">
            {eval_.overallScore}/10
          </div>
          <div className={`inline-flex items-center gap-2 px-4 py-2 rounded-full border text-sm font-semibold mt-2 ${rec.bg} ${rec.color}`}>
            <span>{rec.icon}</span>
            <span>{eval_.hiringRecommendation}</span>
          </div>
          <p className="text-slate-700 dark:text-slate-300 text-sm mt-4 max-w-xl mx-auto leading-relaxed">{eval_.summary}</p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-md transition-colors"
        >
          <h3 className="font-semibold text-slate-900 dark:text-white mb-6 text-base">Competency Score Breakdown</h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 justify-items-center">
            <ScoreRing score={eval_.technicalScore} label="Technical" color="#818cf8" />
            <ScoreRing score={eval_.communicationScore} label="Communication" color="#34d399" />
            <ScoreRing score={eval_.problemSolvingScore} label="Problem Solving" color="#f59e0b" />
            <ScoreRing score={eval_.confidenceScore} label="Confidence" color="#f472b6" />
          </div>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-4">
          <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-md transition-colors">
            <h3 className="font-semibold text-emerald-600 dark:text-emerald-400 mb-4 flex items-center gap-2"><span>💪</span> Key Strengths</h3>
            <ul className="space-y-2">
              {(eval_.strengths || []).map((s, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-slate-700 dark:text-slate-300">
                  <span className="text-emerald-600 dark:text-emerald-400 mt-0.5 font-bold">✓</span> {s}
                </li>
              ))}
            </ul>
          </motion.div>

          <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-md transition-colors">
            <h3 className="font-semibold text-rose-600 dark:text-rose-400 mb-4 flex items-center gap-2"><span>🎯</span> Growth Areas</h3>
            <ul className="space-y-2">
              {(eval_.weaknesses || []).map((w, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-slate-700 dark:text-slate-300">
                  <span className="text-rose-600 dark:text-rose-400 mt-0.5 font-bold">→</span> {w}
                </li>
              ))}
            </ul>
          </motion.div>
        </div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-md transition-colors">
          <h3 className="font-semibold text-slate-900 dark:text-white mb-4">🗺️ Personalized Action Plan</h3>
          <ol className="space-y-3">
            {(eval_.improvementSuggestions || eval_.nextSteps || []).map((s, i) => (
              <li key={i} className="flex items-start gap-3 text-sm text-slate-700 dark:text-slate-300">
                <span className="w-6 h-6 rounded-full bg-indigo-100 dark:bg-indigo-600/30 text-indigo-600 dark:text-indigo-400 border border-indigo-200 dark:border-indigo-500/30 flex-shrink-0 flex items-center justify-center text-xs font-bold">
                  {i + 1}
                </span>
                {s}
              </li>
            ))}
          </ol>
        </motion.div>

        <div className="flex gap-4 justify-center pt-4">
          <button
            onClick={() => navigate('/mock-interview')}
            className="px-8 py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold rounded-xl transition-colors shadow-lg shadow-indigo-600/30"
          >
            Start Another Session
          </button>
          <button
            onClick={() => navigate('/dashboard')}
            className="px-8 py-3 bg-white dark:bg-slate-900 hover:bg-slate-100 dark:hover:bg-slate-800 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 font-semibold rounded-xl transition-colors shadow-sm"
          >
            Dashboard
          </button>
        </div>
      </div>
    </div>
  );
}
